title: There is a Place (066)
description: > 
   Where I can go...
   When I feel low...
   When I feel blue...<br />
   And it's my mind...
   And there's no time...
   When I'm alone <br />
   Lenny Macca (1963)

theme: jekyll-theme-midnight
author: Cicak Bin Kadal
encoding: UTF-8
timezone: Asia/Jakarta

show_downloads: true

# CAN CHANGE
# theme: jekyll-theme-primer
# github: [metadata]
# encoding: UTF-8
# kramdown:
#   input: GFM
#   hard_wrap: false
# future: true
# jailed: false
# gfm_quirks: paragraph_end
# CAN NOT CHANGE
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
